#!/bin/bash

###################################################################################################
# clean
#
# List the drives that have been tagged with the given identifier.
#
# You may use tags for whatever purpose you like. They are a freeform system to let you group
# your drives and more easily look up sets of drives that share things in common.
###################################################################################################

COMMAND_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$COMMAND_PATH/../config"

read -p "Are you sure? This will delete all backups of your FIN computers. [y/n]" -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
    printf "Cleaning backups folder:\n"
    printf "  ╰──▶ ${GREEN}$BACKUPS_PATH${NC}\n\n"

    cd "$BACKUPS_PATH"
    find . -mindepth 1 -name \* -delete
    cd "$PWD"
    important "Done!\n"
else
    important "Aborted.\n"
fi
