#!/bin/bash

###################################################################################################
# findtag
#
# List the drives that have been tagged with the given identifier.
#
# You may use tags for whatever purpose you like. They are a freeform system to let you group
# your drives and more easily look up sets of drives that share things in common.
###################################################################################################

COMMAND_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$COMMAND_PATH/../config"

if [ -z "$1" ]; then
    important "Argument 'tag' is required!\nUsage: $0 <tag>\n";
    exit 1
fi

# Look up any drives with tags matching the query. If there are none, report that nothing was found.
cd "$DRIVES_PATH"
DRIVES="$( find . -mindepth 1 -maxdepth 1 -type d -exec test -f '{}'/tags/$1 \; -print | sort -u | cut -c3-34 )"
if [ ${#DRIVES[@]} -eq 0 ]; then
    important "No matching drives.\n\nDone!\n"
    exit 0
elif [ "$DRIVES" == "" ]; then
    important "No matching drives.\n\nDone!\n"
    exit 0
fi

# Otherwise, report all of the matching drives and their applied apps.
for DRIVE in $DRIVES
do
    if [ -f "$DRIVES_PATH/$DRIVE/.app" ]; then
        APP=$( cat "$DRIVES_PATH/$DRIVE/.app" )
    else
        APP="unapplied"
    fi

    printf "Match: Drive ${RED}$DRIVE${NC} (${GREEN}$APP${NC})!\n"
done

cd $PWD

important "\nDone!\n"
