#!/bin/bash

###################################################################################################
# pull
#
# Update the FIN SDK /drives folder with any new drives found in your FIN computers folder.
#
# This will *only* overwrite the contents of each drive's /data folder. It does this to ensure
# that any persistent data saved to each drive during gameplay will be preserved.
# Everything else should be code.
#
# After new drives are discovered, all drives will automatically be `reapply`ed so any new drives
# appear in /app_drives/unapplied. Existing drives that have been applied to apps will be unchanged.
###################################################################################################

COMMAND_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$COMMAND_PATH/../config"

# Discover drives from FIN computers folder.
if [ "$1" == "--no-clobber" ]; then
    "$COMMANDS_PATH/discover --no-clobber"
else
    "$COMMANDS_PATH/discover"
fi

# Reapply to move any newly discovered drives into the "unapplied" subfolder.
printf "\nReapplying drives:\n"
printf "  ╰──▶ ${GREEN}$APP_DRIVES_PATH${NC}\n\n"
"$COMMANDS_PATH/reapply"

# Not needed since reapply prints it for us.
# echo "Done!"
